apiVersion: v1

kind: Pod
metadata:
  name: db1

spec:
  nodeName: localhost0   # 노드가 없거나, 리소스가 없는 경우 , 파드가 실행되지 않음. 권장X
  containers:
    - name: mysql
      image: mysql:5.7
      env:  # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          value: password

      ports:
        - containerPort: 3306
          name: mysql

      volumeMounts:
        - name: db-volume
          mountPath: /var/lib/mysql
  
  volumes:
    - name: db-volume
      persistentVolumeClaim:
        claimName: db-pvc
