apiVersion: v1
kind: Service
metadata:
  name: "svc-ext"

spec:
#  type: LoadBalancer
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 30007     # 생략 가능

  selector:
    app: httpd-pod
