apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: http-pvc
  
spec:
#  storageClassName: manual     # nfs사용시 생략
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
