apiVersion: v1
kind: PersistentVolume
metadata:
  name: http-pv
  labels:
   # type: local
    type: nfs

spec:
#  storageClassName: manual   # nfs사용시 생략
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.10.200
    path: /mnt/nfs
#  hostPath:
#    path: "/mnt/data2"
