apiVersion: apps/v1
kind: Deployment
metadata:
  name: rs1

spec:
  replicas: 3
  selector:
    matchLabels:
      app: httpd-pod

  template:
   metadata:
     labels:
       app: httpd-pod
   spec:
     containers:
       - name: httpd
         image: httpd
         ports:
           - containerPort: 80
       
         volumeMounts:
           - name: test-volume
             mountPath: /test/

     volumes:
       - name: test-volume

